name: Build and Publish on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle shadowJar
    
    - name: Generate SHA256 File
      run: sha256sum build/libs/*.jar > build/libs/sha256sum.txt

    - name: Get Game Version From Gradle
      id: get_game_version
      run: |
        export GAME_VERSION=$(grep -r -oP '(?<=org\.spigotmc:spigot-api:)\d+\.\d+\.?\d*' build.gradle | head -n1)
        echo "::set-output name=game_version::$GAME_VERSION"

    - name: Get Version Type
      id: get_version_type
      run: |
        if [[ "${{ github.event.release.version }}" == *"alpha"* ]]; then
          VERSION_TYPE="alpha"
        elif [[ "${{ github.event.release.version }}" == *"beta"* ]]; then
          VERSION_TYPE="beta"
        else
          VERSION_TYPE="release"
        fi

        echo "::set-output name=version_type::$VERSION_TYPE"

    - uses: Kir-Antipov/mc-publish@v3.2
      with:
        loaders: |
          spigot
          bukkit
          paper

        game-versions: |
          ${{ steps.get_game_version.outputs.game_version }}
        version-type: ${{ steps.get_version_type.outputs.version_type }}
        version-resolver: exact
        fail-mode: skip

        files-secondary: build/libs/*sha256sum.txt

        modrinth-id: VxyZQvPV
        modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

        curseforge-id: 849534
        curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

        github-token: ${{ secrets.GITHUB_TOKEN }}