name: Build and Publish on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Get Game Version From Gradle
      id: get_game_version
      run: |
        export GAME_VERSION=$(grep -r -oP '(?<=org\.spigotmc:spigot-api:)\d+\.\d+\.\d+' build.gradle | head -n1)
        echo "GAME_VERSION=$GAME_VERSION" >> $GITHUB_ENV

    - name: Get Version Type
      id: get_version_type
      run: |
        if [[ "${{ github.event.release.version }}" == *"alpha"* ]]; then
          VERSION_TYPE="alpha"
        elif [[ "${{ github.event.release.version }}" == *"beta"* ]]; then
          VERSION_TYPE="beta"
        else
          VERSION_TYPE="release"
        fi

        echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle shadowJar

    - uses: Kir-Antipov/mc-publish@v3.2
      with:
        game-versions:
          - ${{ env.GAME_VERSION }}
        version-type: ${{ env.VERSION_TYPE }}
        loaders: |
          spigot
          bukkit
          paper

        modrinth-id: VxyZQvPV
        modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

        curseforge-id: 849534
        curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

        github-token: ${{ secrets.GITHUB_TOKEN }}